services:
  db:
    container_name: postgres_container
    image: postgres:16
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: MYDB
      TZ: Asia/Bangkok
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d MYDB" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - my-networks

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"
      NIFI_SENSITIVE_PROPS_KEY: admin_password
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin_password
      TZ: Asia/Bangkok
    volumes:
      - ./data/dropzone:/opt/nifi/dropzone
      - ./data/archive:/opt/nifi/archive
      - ./data/error:/opt/nifi/error
      - ./jdbc/postgresql-42.7.3.jar:/opt/nifi/nifi-current/lib/postgresql-42.7.3.jar
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-networks

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: lab_pgadmin_secure
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-networks

  af:
    container_name: airflow_container
    image: apache/airflow:latest
    ports:
      - "8001:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      TZ: Asia/Bangkok
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./sql:/opt/airflow/sql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-networks
    command: >
      bash -c "airflow db migrate && airflow standalone"

  flask_app:
    build: ./flask_app
    container_name: lab_flask_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: MYDB
      DB_USER: postgres
      DB_PASSWORD: password123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge
